from django.test import LiveServerTestCase
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
class NewVistorTest(LiveServerTestCase):
    def setUp(self):
        self.browser = webdriver.Firefox()
    def tearDown(self):
        self.browser.quit()
    def check_for_row_in_list_table(self, row_text):
        table = self.browser.find_element_by_id('id_list_table')
        rows = table.find_elements_by_tag_name('tr')
        self.assertIn(row_text, [row.text for row in rows])
    def test_can_start_a_list_and_retrieve_it_later(self):
        # Someone heard about a list application
        # He went to the home page of this application
        self.browser.get(self.live_server_url)
        # He noticed the title and header containing a word "To-Do"
        self.assertIn('To-Do', self.browser.title)
        header_text = self.browser.find_element_by_tag_name('h1').text

        self.assertIn('To-Do', header_text)
        # The applicatio invites him to input a to-do list
        inputbox = self.browser.find_element_by_id('id_new_item')
        self.assertEqual(
            inputbox.get_attribute('placeholder'),
            'Enter a to-do item'
        )
        # He type "Buy peacock feathers" in a input box
        inputbox.send_keys('Buy peacock feathers')
        # He hit enter key and the page updated
        # The table shows "1: Buy peacock feathers"
        inputbox.send_keys(Keys.ENTER)
        time.sleep(1)
        self.check_for_row_in_list_table('1: Buy peacock feathers')
        # Then the page showed another input box which could be typed other to-do list
        # He typed "Use peacock feathers to make a fly"
        inputbox = self.browser.find_element_by_id('id_new_item')
        inputbox.send_keys('Use peacock feathers to make a fly')
        inputbox.send_keys(Keys.ENTER)
        time.sleep(1)
        # Then the page updated again, the list show those two tasks
        self.check_for_row_in_list_table('1: Buy peacock feathers')
        self.check_for_row_in_list_table('2: Use peacock feathers to make a fly')
        # He wanted to know if this website could remember his lists
        # He saw a unique URL generated by the website
        # And there was a description about this function
        self.fail('Finish the test!')
        # He accessed that URL and found his list was still there
        # He was satisfried and went to sleep